### ISSUE TITLE
Syntax error with zsh

### ISSUE THREAD

**Issue by statox** [aws-samples/aws2tf#10]
When running `./aws2tf.sh` on zsh I get a syntax error:

    ./aws2tf.sh: 82: Syntax error: "(" unexpected

The context of the line 82 is:

    79 shift $((OPTIND-1))¶
    80 ¶
    81 trap ctrl_c INT¶
    82 ¶
    83 function ctrl_c() {¶
    84         echo "Requested to stop."¶
    85         exit 1¶
    86 }¶

I'm not sure what's wrong but setting a proper shebang solves the issue:

    #!/usr/bin/env bash

Do you think it's a good enough fix? If so I can create a PR

**Comment by awsandy** [comment]
yes please do
