### ISSUE TITLE
--no-verify-ssl option 

### ISSUE THREAD

**Issue by yesbash** [aws-samples/aws2tf#13]
s$ sh aws2tf.sh --no-verify-ssl
Usage: aws2tf.sh [-p <profile>] [-c] [-v] [-r <region>] [-t <type>] [-h] [-d] [-s] <stack name>

--no-verify-ssl is not a valid option

**Comment by awsandy** [comment]
This is by design - The right approach I suggest is to include the appropriate Amazon and intermediate certificates into your environment.
