### ISSUE TITLE
-c yes continues even if .terraform directory is missing

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#18]
if for some reason the `.terraform` directory is missing and the parameter `-c yes` was passed to `aws2tf` then it will continue running and fail to import with this error over and over again
```
ls: cannot access '../.terraform': No such file or directory
pi2 using initing TF provider
aws_iam_instance_profile ecsInstanceRole import
```

**Comment by awsandy** [comment]
I'll add a check for -c - to ensure the previous run exists

**Comment by awsandy** [comment]
added check
