### ISSUE TITLE
docs: terraform state is a local file

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#19]
initial impression of reading the readme was that the state file was for the already existing state file. in my case i have it in s3.

when actually running it, i discovered 
- i had to run aws2tf in my local cloned copy
- it created a directory for everything including the local state file (this means it wont corrupt an already existing state file elsewhere)
- it wont complement the already existing tf files i wrote for my resources but start from scratch

**Comment by awsandy** [comment]
Correct aws2tf uses it's own local state file - I'll update the docs to clarify. Thank you

**Comment by awsandy** [comment]
docs updated
