### ISSUE TITLE
Errors first time through

### ISSUE THREAD

**Issue by bcorner13** [aws-samples/aws2tf#2]
First run through received the following error messages.  Tool seems to run otherwise.
`./aws2tf.sh 
Region not specified - Getting region from aws cli =
us-east-1
Cleaning generated/tf.727535128727
 
Account ID = 727535128727
AWS Resource Group Filter = 
Region = us-east-1
AWS Profile = dev
Extract KMS Secrets to .tf files (insecure) = no
Fast Forward = no
Verify only = no
Type filter = 
Combine = no
AWS command = aws --profile dev --region us-east-1 --output json 
 
terraform { 
  required_providers {
   aws = {
     source  = "hashicorp/aws"
      version = "= 3.45.0"
    }
  }
}

provider "aws" {
 region = "us-east-1" 
 shared_credentials_file = "~/.aws/credentials" 
 profile = "dev" 
}
/Users/bradcorner/github/aws2tf/generated/tf.727535128727
terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "3.45.0"...
- Installing hashicorp/aws v3.45.0...
- Installed hashicorp/aws v3.45.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
aws.tf		data		import.log
Thu Sep 16 13:00:05 EDT 2021
t=
loop through providers
type-get-transitgw.sh
post fix vpn
ls: aws_ec2_transit_gateway_vpn_attachment*.tf: No such file or directory
**** Type Validate Call ****
Success! The configuration is valid.

Success! The configuration is valid.

type-get-transitgw.sh runtime 7 seconds
010-get-organization.sh
aws --profile dev --region us-east-1 --output json organizations describe-organization
aws_organizations_organization o-fva3nsw4un import
╷
│ Error: error listing AWS Organization (o-fva3nsw4un) accounts: AccessDeniedException: You don't have permissions to access this resource.
│ 
│ 
╵

aws_organizations_organization.o-fva3nsw4un: Importing from ID "o-fva3nsw4un"...
aws_organizations_organization.o-fva3nsw4un: Import prepared!
No state file was found!

State management commands require a state file. Run this command
in a directory where Terraform has been run or use the -state flag
to point the command to a specific state location.
jq: error (at <stdin>:1): Cannot iterate over null (null)
Found Error: │ Error: error listing AWS Organization (o-fva3nsw4un) accounts: AccessDeniedException: You don't have permissions to access this resource. exiting .... (pass for now)
Success! The configuration is valid.

010-get-organization.sh runtime 6 seconds
011-get-orgaccounts.sh
aws --profile dev --region us-east-1 --output json organizations list-accounts

An error occurred (AccessDeniedException) when calling the ListAccounts operation: You don't have permissions to access this resource.
This is not an AWS organizations account
Found Error: │ Error: error listing AWS Organization (o-fva3nsw4un) accounts: AccessDeniedException: You don't have permissions to access this resource. exiting .... (pass for now)
Success! The configuration is valid.

011-get-orgaccounts.sh runtime 2 seconds
012-get-org-ou.sh

An error occurred (AccessDeniedException) when calling the ListRoots operation: You don't have permissions to access this resource.

Found Error: │ Error: error listing AWS Organization (o-fva3nsw4un) accounts: AccessDeniedException: You don't have permissions to access this resource. exiting .... (pass for now)
Success! The configuration is valid.

012-get-org-ou.sh runtime 2 seconds
013-get-org-policies.sh

An error occurred (AccessDeniedException) when calling the ListPolicies operation: You don't have permissions to access this resource.
This is not an AWS organizations account
Found Error: │ Error: error listing AWS Organization (o-fva3nsw4un) accounts: AccessDeniedException: You don't have permissions to access this resource. exiting .... (pass for now)
Success! The configuration is valid.

013-get-org-policies.sh runtime 2 seconds
021-get-sso-permsets.sh
Refresh ..
╷
│ Error: error reading SSO Instances: AccessDeniedException: 
│ 
│   with data.aws_ssoadmin_instances.sso,
│   on data__aws_ssoadmin_instances__sso.tf line 1, in data "aws_ssoadmin_instances" "sso":
│    1: data "aws_ssoadmin_instances" "sso" {}
│ 
╵
No state file was found!

State management commands require a state file. Run this command
in a directory where Terraform has been run or use the -state flag
to point the command to a specific state location.

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument --instance-arn: expected one argument

This is not an AWS organizations account
Found Error: │ Error: error listing AWS Organization (o-fva3nsw4un) accounts: AccessDeniedException: You don't have permissions to access this resource. exiting .... (pass for now)
Found Error: │ Error: error reading SSO Instances: AccessDeniedException:  exiting .... (pass for now)
Success! The configuration is valid.

021-get-sso-permsets.sh runtime 6 seconds
030-get-iam-users.sh
skipping 030-get-iam-users.sh
034-get-iam-groups.sh
skipping 034-get-iam-groups.sh
050-get-iam-roles.sh
skipping 050-get-iam-roles.sh
051-get-iam-role-policies.sh
skipping 051-get-iam-role-policies.sh
052-get-iam-attached-role-policies.sh
skipping 052-get-iam-attached-role-policies.sh
055-get-iam-policies.sh
skipping 055-get-iam-policies.sh
056-get-instance-profile.sh
aws_iam_instance_profile AmazonSSMRoleForInstancesQuickSetup import
aws_iam_instance_profile aws-elasticbeanstalk-ec2-role import
aws_iam_instance_profile aws-opsworks-cm-ec2-role import
aws_iam_instance_profile aws-opsworks-ec2-role import
aws_iam_instance_profile ec2-prometheus import
aws_iam_instance_profile ecsInstanceRole import
aws_iam_instance_profile ECS_SSM import
aws_iam_instance_profile elasticRole import
aws_iam_instance_profile gspice-dev-EC2InstanceProfile-YHFOR2JGHW0K import
aws_iam_instance_profile gspice-qacloud-EC2InstanceProfile-W33238ZJ52VE import
aws_iam_instance_profile Harish-WIndows-Test-ECSInstanceProfile-13BI2CVRHNYMI import
aws_iam_instance_profile kubernetes-master import
aws_iam_instance_profile kubernetes-minion import
aws_iam_instance_profile loadtest-transcode-new-EC2InstanceProfile-1CFDI3Y6JOMO2 import
aws_iam_instance_profile MasterRole import
aws_iam_instance_profile rev-api-gateway-loadtest-EC2InstanceProfile-145SDR1HW6E7Z import
aws_iam_instance_profile rev-api-gateway-qacloud-EC2InstanceProfile-1BUQO77YUVYIW import
aws_iam_instance_profile rev-apigateway-ec2Role import
aws_iam_instance_profile rev-video-ingester-dev-EC2InstanceProfile-UGYC4FVHEXLF import
aws_iam_instance_profile rev-video-ingester-loadtest1-EC2InstanceProfile-16VWI8RBO3NQA import
aws_iam_instance_profile rev-video-ingester-qacloud-EC2InstanceProfile-UFTNY1BX33ZG import
aws_iam_instance_profile RevS3Access import
aws_iam_instance_profile SparkBot-QA-EC2InstanceProfile-132TXLCEYJB8D import
aws_iam_instance_profile transcode-dev-EC2InstanceProfile-GZQE1RFBVTLO import
aws_iam_instance_profile Transcode-QA-EC2InstanceProfile-1HMHANNWS684A import
aws_iam_instance_profile vbrick-ec2-audit import
aws_iam_instance_profile vbrick-ec2-bastion import
aws_iam_instance_profile vbrick-ec2-elasticsearch import
aws_iam_instance_profile vbrick-ec2-haproxy import
aws_iam_instance_profile vbrick-ec2-mongodb import
aws_iam_instance_profile vbrick-ec2-rabbitmq import
aws_iam_instance_profile vbrick-ec2-rev import
aws_iam_instance_profile vbrick-ec2-revanalytics import
aws_iam_instance_profile vbrick-ec2-waf import
Waiting for 34 Terraform imports
`

**Comment by awsandy** [comment]
Fixed that specific error - just working through other similar problems for cases when the user of aws2tf doen't have full access.

**Comment by awsandy** [comment]
closing
