### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#21]
would it be possible to direct errors to an error log at the same time as to the terminal?

in an account with lots of resources, leaving aws2tf to run for a while and then coming back, the errors get lost in the scroll back. having an error log would be helpful to identify what is critical and what isnt

**Comment by awsandy** [comment]
There are logged in the "import.log" file in generated/tf* directory.

**Comment by awsandy** [comment]
if you add "-d yes"

aws2tf will stop when the first error occurs

**Comment by marafa-sugarcrm** [comment]
> if you add "-d yes"
> 
> aws2tf will stop when the first error occurs

NICE! thank you
