### ISSUE TITLE
Error: only lowercase alphanumeric characters and hyphens allowed in parameter group "name"

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#22]
i am getting this error on all the default groups

```hcl

Error: only lowercase alphanumeric characters and hyphens allowed in parameter group "name"

  with aws_rds_cluster_parameter_group.default_aurora5_6,
  on aws_rds_cluster_parameter_group__default_aurora5_6.tf line 6, in resource "aws_rds_cluster_parameter_group" "default_aurora5_6":
   6:   name        = "default.aurora5.6"

```

**Comment by awsandy** [comment]
Fix committed

**Comment by marafa-sugarcrm** [comment]
still seeing the issue

**Comment by awsandy** [comment]
dump question but - done a git pull recently ?

**Comment by awsandy** [comment]
If you have please post the output from the aws_rds_cluster_parameter_group and the following lines before it moves on to the next resource or stops if you have "-d yes"

**Comment by marafa-sugarcrm** [comment]
yes. i pulled as soon as i saw your comment.

is this what. you want?

```
Error: only lowercase alphanumeric characters and hyphens allowed in parameter group "name"

  with aws_rds_cluster_parameter_group.default_aurora-mysql5_7,
  on aws_rds_cluster_parameter_group__default_aurora-mysql5_7.tf line 6, in resource "aws_rds_cluster_parameter_group" "default_aurora-mysql5_7":
   6:   name        = "default.aurora-mysql5.7"


Error: only lowercase alphanumeric characters and hyphens allowed in parameter group "name"

  with aws_rds_cluster_parameter_group.default_aurora-mysql8_0,
  on aws_rds_cluster_parameter_group__default_aurora-mysql8_0.tf line 6, in resource "aws_rds_cluster_parameter_group" "default_aurora-mysql8_0":
   6:   name        = "default.aurora-mysql8.0"


Error: only lowercase alphanumeric characters and hyphens allowed in parameter group "name"

  with aws_rds_cluster_parameter_group.default_aurora5_6,
  on aws_rds_cluster_parameter_group__default_aurora5_6.tf line 6, in resource "aws_rds_cluster_parameter_group" "default_aurora5_6":
   6:   name        = "default.aurora5.6"
```

**Comment by awsandy** [comment]
to help me debug this:

go to the directory that the tf files / state are being generated

cd generated/tf.<youraccount>_<youregion>
rm aws_rds_cluster_parameter_group*.tf
export AWS=aws

../../scripts/612*

and post the output here:


... when I do this I just get:

% ../../scripts/612*
aws rds describe-db-cluster-parameter-groups
count=2
aws_rds_cluster_parameter_group default.aurora-mysql5.7
skipping a default param group
aws_rds_cluster_parameter_group default.aurora-postgresql11
skipping a default param group


ie. it skips default parameter groups

**Comment by awsandy** [comment]
On the next clean run (without -c yes) this should be ok
