### ISSUE TITLE
Error: Conflicting configuration arguments -> Stacksets

### ISSUE THREAD

**Issue by ahkai86** [aws-samples/aws2tf#29]
Hi hello! understand that the AWS Stackset is still in progress, any ways to exclude all components related to AWS StackSets during the run?

I tried to run the commands "./aws2tf.sh -t iam'  , 
and encountered this error:
 
`│ Error: Conflicting configuration arguments
│ 
│   with aws_iam_role.stacksets-exec-1c62acbfe1b28a0ec07ae0d849260fb4,
│   on aws_iam_role__stacksets-exec-1c62acbfe1b28a0ec07ae0d849260fb4.tf line 26, in resource "aws_iam_role" "stacksets-exec-1c62acbfe1b28a0ec07ae0d849260fb4":
│   26:     name                  = "stacksets-exec-1c62acbfe1b28a0ec07ae0d849260fb4"
│ 
│ "name": conflicts with name_prefix`

Thanks so much!

**Comment by awsandy** [comment]
fix committed for this, which should solve the above, this was more a generic error.

The stack set development stuff is related to the -s option (reads a deployed stack set and converts to Terraform)

You can also use -i with -t iam to pick out specific roles

./aws2tf.sh -t iam -i myrolename

**Comment by ahkai86** [comment]
Hi Andy, thanks for the prompt reply and changes! Now its working all good =)

Have a great week ahead, cheers!

**Comment by awsandy** [comment]
Thank you
