### ISSUE TITLE
Error: Reference to undeclared resource (cloudtrail & routetable)

### ISSUE THREAD

**Issue by ahkai86** [aws-samples/aws2tf#32]
Encountered new errors on cloudwatch log group & aws Routetable by executing "./aws2tf.sh -v yes"

```
│ Error: Reference to undeclared resource
│ 
│   on aws_cloudtrail__aws-controltower-BaselineCloudTrail.tf line 4, in resource "aws_cloudtrail" "aws-controltower-BaselineCloudTrail":
│    4: cloud_watch_logs_group_arn = aws_cloudwatch_log_group.aws-controltower_CloudTrailLogs.arn
│ 
│ A managed resource "aws_cloudwatch_log_group" "aws-controltower_CloudTrailLogs" has not been declared in the root module.
╵
╷
│ Error: Reference to undeclared resource
│ 
│   on aws_route_table__rtb-0fcb1c52f40ddaae7.tf line 16, in resource "aws_route_table" "rtb-0fcb1c52f40ddaae7":
│   16: nat_gateway_id = aws_nat_gateway.nat-039de67cc3ebb5728.id
│ 
│ A managed resource "aws_nat_gateway" "nat-039de67cc3ebb5728" has not been declared in the root module.`
```

**Comment by awsandy** [comment]
committed fixes for these two - thanks for reporting them !

**Comment by ahkai86** [comment]
Still encountered this issue with cloudwatch log group with latest code:

│ Error: Reference to undeclared resource
│ 
│   on aws_cloudtrail__aws-controltower-BaselineCloudTrail.tf line 4, in resource "aws_cloudtrail" "aws-controltower-BaselineCloudTrail":
│    4: cloud_watch_logs_group_arn = format("%s:*",aws_cloudwatch_log_group.aws-controltower_CloudTrailLogs.arn)
│ 
│ A managed resource "aws_cloudwatch_log_group" "aws-controltower_CloudTrailLogs" has not been declared in the root module.

**Comment by awsandy** [comment]
committed further changes to try and catch this

**Comment by ahkai86** [comment]
yes thanks andy! your commit has fixed the issue! thanks again v much!
