### ISSUE TITLE
Error: Invalid escape sequence

### ISSUE THREAD

**Issue by ahkai86** [aws-samples/aws2tf#33]
Hi Andy, executing the latest code with "./aws2tf.sh -v yes"

>  │ Error: Invalid escape sequence
│ 
│   on /Users/kj/Desktop/aws2tf-master/generated/tf.xxxxxxxxxxxx_ap-southeast-1/aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf line 22, in resource "aws_cloudwatch_event_target" "default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget":
│   22: input_template = "={ title: Auto Scaling EC2 instance launch failed, description: CloudWatch Event Rule SSMOpsItems-Autoscaling-instance-launch-failure was triggered. Your EC2 instance launch has failed. See below for more details., source: EC2 Auto Scaling, category: Availability, severity:2, resources: <resources>, operationalData: { /aws/dedup: {type: SearchableString, value: {\dedupString\:\SSMOpsItems-Autoscaling-instance-launch-failure\}}, /aws/automations: { value: [ { \automationType\: \AWS:SSM:Automation\, \automationId\: \AWS-ASGEnterStandby\ }, { \automationType\: \AWS:SSM:Automation\, \automationId\: \AWS-ASGExitStandby\ } ] }, autoscaling-group-name: {value: <autoscaling-group-name>}, status-message: {value: <status-message>}, start-time: {value: <start-time>}, end-time: {value: <end-time>}, cause: {value: <cause>}} }"
│ 
│ The symbol ":" is not a valid escape sequence selector.

> The symbol "S" is not a valid escape sequence selector.

> The symbol "}" is not a valid escape sequence selector.

> The symbol ":" is not a valid escape sequence selector.

> The symbol "A" is not a valid escape sequence selector.

> The symbol "," is not a valid escape sequence selector.

> The symbol ":" is not a valid escape sequence selector.

> The symbol "A" is not a valid escape sequence selector.

> The symbol "a" is not a valid escape sequence selector.

> The symbol ":" is not a valid escape sequence selector.

> The symbol "A" is not a valid escape sequence selector.

>  The symbol "d" is not a valid escape sequence selector.

> The symbol ":" is not a valid escape sequence selector.

> The symbol "S" is not a valid escape sequence selector.

**Comment by awsandy** [comment]
Hmm - I'm having trouble reproducing this one - could you 

delete the file aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf

and then do a: 

terraform state show aws_cloudwatch_event_target.default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget

(redact what you need to) - and post the output from the above here please.

**Comment by awsandy** [comment]
committed a potential fix - quite hard to reproduce this one.

If it still errors:

delete the offending aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf     file 

- and post the (redacted) output of 

terraform state show aws_cloudwatch_event_target.default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget

That should help me track it down.

**Comment by ahkai86** [comment]
Rule name:
SSMOpsItems-Autoscaling-instance-launch-failure

Description:
Rule for SSM OpsCenter to create OpsItems when EC2 Auto Scaling instance launch failed

**Comment by awsandy** [comment]
Can I get some more of the error / screen output from this one please.
