### ISSUE TITLE
cloudwatch: Found Error: Error: Missing source file for snapshot exiting

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#36]
i got an error on cloudwatch while running aws2tf
```
aws_cloudwatch_log_group <redacted> tf files
Found Error: Error: Missing source file for snapshot exiting ....
```

**Comment by awsandy** [comment]
I think this one is caused by a race condition when doing parallel imports.
Committed a change that turns down the number of parallel imports that are allowed.
It might help avoid this error

You can also rerun with ./aws2tf.sh -c yes - to jump over tf files already imported

**Comment by marafa-sugarcrm** [comment]
i am using `-c yes`

**Comment by awsandy** [comment]
are you still seeing the error ?

**Comment by marafa-sugarcrm** [comment]
no. cloudwatch files were generated a few days ago
