### ISSUE TITLE
Error: invalid resource name

### ISSUE THREAD

**Issue by ahkai86** [aws-samples/aws2tf#37]
Hi Andy, encountered the following:

Error: Invalid resource name

  on aws_codepipeline__5StagePipeline.tf line 1, in resource "aws_codepipeline" "5StagePipeline":
   1: resource "aws_codepipeline" "5StagePipeline" {}

A name must start with a letter or underscore and may contain only letters,
digits, underscores, and dashes.

**Comment by awsandy** [comment]
committed fix for this one
