### ISSUE TITLE
Error: Resource already managed by Terraform exiting

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#38]
got this error and i am not even sure on what kind of resource this is 
```sh
Instance is cloud9 skipping .....
breaking ...
Found Error: │ Error: Resource already managed by Terraform exiting ....
```

**Comment by awsandy** [comment]
Are you running with -d ?   what does your ./aws2tf.sh ....... command look like ?

I'd expect an exit on that error only when using the debug (-d) flag

**Comment by awsandy** [comment]
committed change with extra output when exiting on this condition - will help confirm my theory

**Comment by marafa-sugarcrm** [comment]
this is what i got now 
```
Instance is cloud9 skipping .....
breaking from ec2 ...
Found Error: │ Error: Resource already managed by Terraform
debug flag is on so exiting ....
```

and yes i do have `-d yes` enabled

**Comment by awsandy** [comment]
If you remove the -d yes it will continue.

I'll look to ignore that particular error shortly as I guess you are using -c yes as well

**Comment by awsandy** [comment]
committed fix - so it ignores Resource already managed by Terraform  - even with -d yes
