### ISSUE TITLE
terraform init triggers repeated download of AWS provider

### ISSUE THREAD

**Issue by arcaven** [aws-samples/aws2tf#4]
in the base and in a variety of loops, the terraform aws provider is downloaded over and over
on slow links this may significantly slow the session(s) and because it is cleared each time and does not persist across runs, you download many more times than is required, especially given that the version of the aws provider is fixed

it is also difficult from the current console output to understand why the aws provider is downloaded over and over

pull request coming

**Comment by awsandy** [comment]
Thank you for this - looking to merge soon

**Comment by awsandy** [comment]
Fixed - in the end I simply added some soft links to parallel_import.sh - so this works for all parallel imports (not just subnets)
