### ISSUE TITLE
-d debug

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#42]
is it intentional that `-d` always exits on any error?

```
Found Error: │ Error: error listing AWS Organization (o-<redacted>) accounts: AccessDeniedException: You don't have permissions to access this resource.
debug flag is on so exiting ....
```

**Comment by awsandy** [comment]
Yes, you'd typically use aws2tf without -d

I only use it to stop on the first error when I'm debugging some unexpected error.
