### ISSUE TITLE
 The argument "target_prefix" is required, but no definition was found.

### ISSUE THREAD

**Issue by Laxman-SM** [aws-samples/aws2tf#47]
Hi Andy,
I found this below mentioned while executing 

./aws2tf.sh -t s3

../../scripts/fix-undec.sh: line 73: syntax error near unexpected token `[['
../../scripts/fix-undec.sh: line 73: `            if [[ $tft == "aws_sagemaker_image" ]] || [[ $tft == "aws_lambda_function" ]] || [[ $tft == "aws_dynamodb_table" ]] || [[ $tft == "aws_sns_topic" ]] [[ $tft == "aws_iam_role" ]] || [[ $tft == "aws_codepipeline" ]]; then'
╷
│ Error: Missing required argument
│ 
│   on aws_s3_bucket_xxxxxxx-us-west-2.tf line 2, in resource "aws_s3_bucket_logging" "b_aws-controltower-logs-xxxxxxxx-us-west-2":
│    2: resource "aws_s3_bucket_logging" "b_aws-controltower-logs-xxxxxxxxx-us-west-2" {
│ 
│ The argument "target_prefix" is required, but no definition was found.

 Error: Reference to undeclared resource

**Comment by awsandy** [comment]
ok - fixed via the test cases here - hopefully for you too..... changes committed

**Comment by Laxman-SM** [comment]
Thanks you @awsandy for your response. Above mentioned issue resolved.
