### ISSUE TITLE
│ Error: Missing required argument with s3

### ISSUE THREAD

**Issue by Laxman-SM** [aws-samples/aws2tf#48]
HI, I got below mentioned issue while executing command:

./aws2tf.sh -t s3 -r us-west-2  -p default

aws_kms_key.k_3b1690bf-xxxxxx-45c3-a056-xxxxxxxxx: Importing from ID "3b1690bf-xxxxx-xxxxxx-xxxx-7a715exxxxxxx"...
aws_kms_alias alias/uat-xxxxxx-flow-logs
aws_kms_alias.alias_uat-xxxxxxxxx-flow-logs: Importing from ID "alias/uat-xxxxxxx-flow-logs"...
aws_kms_key xxxxxxx0bf-xxxx0-45c3-a056-xxxxxxxxx
aws_kms_key__k_xxxxxxxxxx0-45c3-a056-xxxxxxx.tf exists already skipping ...

Consolidated state aws_s3_bucket_versioning.b_uat-xxxxx-flow-logs
Consolidated state aws_s3_bucket_versioning.b_uat3-alb-logs
run cross checker
import.log adjust
--> Validate Fixer
** Undeclared Fix: aws_kms_key.k_uat-xxxxxx-flow-logs.arn -- 
╷
│ Error: Missing required argument
│ 
│   on aws_s3_bucket_lifecycle_configuration__b_uat-xxxxx-flow-logs.tf line 5, in resource "aws_s3_bucket_lifecycle_configuration" "b_uat-xxxxxxx-flow-logs":
│    5:     rule {
│ 
│ The argument "id" is required, but no definition was found.
╵
erraform Refresh ...
Terraform Plan ...

Error: Missing required argument

  on aws_s3_bucket_lifecycle_configuration__b_uat-xxxxxx-flow-logs.tf line 5, in resource "aws_s3_bucket_lifecycle_configuration" "b_uat-xxxxxxx-flow-logs":
   5:   rule {

The argument "id" is required, but no definition was found.

**Comment by awsandy** [comment]
Committed change that should fix this one.
