### ISSUE TITLE
cant find ec2 after the run

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#49]
i ran aws2tf with `-v yes` as the parameter

i see this in the log
```
imp.log:../../scripts/251-get-ec2-instances.sh: line 208: ../../scripts/056-get-instance-profile.sh: No such file or directory
```

**Comment by awsandy** [comment]
Just committed change that should fix this one.

**Comment by marafa-sugarcrm** [comment]
i still cannot find any ec2 resources

**Comment by awsandy** [comment]
To find an EC2 resource - they must be in the running state, also cloud9 and EKS EC@ instances will be ignored (as these are found elsewhere.

Are your instances running ?

You can also try for one instance you think aws2tf is failing to pick up  - using type ec2 and pass the instance id with -i
./aws2tf.sh -t ec2 -i i-xxxxxxxxx

This will pick up both running and stopped instances.

Let me know how that goes and any output you get please.

**Comment by marafa-sugarcrm** [comment]
this happened
```bash

250-get-ec2-host.sh runtime 7 seconds
-------------------------------------------------------------------
. ../../scripts/251-get-ec2-instances.sh
aws_instance i-???
aws_instance.i-???: Importing from ID "i-???"...
last line     } 92
Waiting for 1 Terraform imports
```
also .. it only found one of 3 instances i had in that region
this is the contents of the script for that instance
```
��e%
```

**Comment by awsandy** [comment]
committed change that will also pick up stopped instances - as you didn't say they were all running ?

Also if it still fails to get an instance - take a note of the instance ID and try:

./aws2tf.sh -t ec2 -i i-????

**Comment by marafa-sugarcrm** [comment]
i have 3 _running_ instances. none were seen


aws2tf output of `./aws2tf.sh  -t ec2 -i i-???` :
```
. ../../scripts/251-get-ec2-instances.sh i-???
aws_instance i-???
aws_instance.i-???: Importing from ID "i-???"...
Waiting for 1 Terraform imports
Importing aws_vpc ...
```

`terraform state show i-???` shows the node

`ls *ec2*` does not show any files

**Comment by awsandy** [comment]
Are those EC2 instances part of an autoscaling group ?

check with:

aws ec2 describe-instances --filters "Name=tag-key,Values=aws:autoscaling*" | grep InstanceId

**Comment by marafa-sugarcrm** [comment]
no. they are standalone ec2 instances

**Comment by marafa-sugarcrm** [comment]
1. i see this in the output  `aws --profile addoptify --region eu-west-1 --output json  ec2 describe-hosts --host-ids i-??? : You don't have access for this resource`
2. i do see 2 "new" files 
[aws_instance__i-.txt](https://github.com/aws-samples/aws2tf/files/11727491/aws_instance__i-.txt)
[aws_instance__i-.tf.txt](https://github.com/aws-samples/aws2tf/files/11727492/aws_instance__i-.tf.txt)
3. i do NOT see anything with `ls *ec2*`

**Comment by marafa-sugarcrm** [comment]
in addition to the above comment. it only gets the 1st (first) instance in the region and then continues on to vpc stuff

**Comment by marafa-sugarcrm** [comment]
me bad. it took about half an hour but it managed to get all the instances in the region. 

thank you
