### ISSUE TITLE
improve speed when continuing

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#53]
disclaimer: i have not verified any of this

it seems like when using `-c yes` the speed of the check is slightly faster than the speed of importing. which isnt much.

can we speed up the check to skip already imported files/states

**Comment by awsandy** [comment]
This is expected - the "-c yes" option will ensure existing terraform state form previous runs is not deleted, this means the state is not imported  (as it already exists)

You can also use the fast forward option  "-f yes" which skips whole resources if they have already been imported in the previous run. (eg. jumps over all the s3 reports - if that section was completed in the last run)

**Comment by marafa-sugarcrm** [comment]
thank you!

**Comment by marafa-sugarcrm** [comment]
i have been running this for about a week now and only imported like 28 instances and 100 SG and about 500 SG rules for just one region . 
i am using `-t ec2 -c yes -f yes`

how do i speed things up ?

**Comment by awsandy** [comment]
For now the fastest way is:


Use AWS Cloud9 (or an EC2 instance) - and put it in the same region as you are trying to import from. (Going cross-region will be very slow).

Far less important - 4 (or more) cores will help the parallel operations

Also:

over time:

a. I'll get more of what aws2tf does to use parallel imports
and 
b. I'm looking at a dramatically faster option - but that will mandate using python.
