### ISSUE TITLE
continue with `-c yes` even with .terraform directory is missing

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#54]
when using `-c yes` on a brand new account or region, i get this message

```
There doesn't appear to be a previous run for aws2tf
missing .terraform directory in 197710756924
exiting ....
```

my ask is to instead of exiting, to merely print this non fatal warning and continue

why?
when working on regions with a large amount of resources, the script may need to be run multiple times, and with a human, the previous command in history may actually be the original without the `-c yes` meaning that we are actually starting over from scratch

**Comment by awsandy** [comment]
You can't use "-c yes" on a new account and region - it can only be used when you have had a previous run.

The "-c yes" mean - continue from a previous run.

That is what it was looking for by checking for the ".terraform" directory existing.

**Comment by marafa-sugarcrm** [comment]
my bad. 
now that aws2tf has determined that `-c yes` wont work. continue on by disabling the switch

**Comment by awsandy** [comment]
cool
