### ISSUE TITLE
sts output in aws2tf.sh assumes JSON

### ISSUE THREAD

**Issue by mysticole928** [aws-samples/aws2tf#56]
This command gets the AWS account information.

My default output for the CLI is text.  This cause it to crash.

```shell
aws sts get-caller-identity | jq .Account | tr -d '"'
```

I changed this line in the script to:

```shell
aws sts get-caller-identity --output json | jq .Account | tr -d '"'
```

The error went away.

**Comment by awsandy** [comment]
incorporated --output json as suggested.

Thank you
