### ISSUE TITLE
aws_cloudwatch_metric_alarm is not hcl

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#59]
aws_cloudwatch_metric_alarm is not hcl. instead i got this and it is breaking all other resources

```
# File generated by aws2tf see https://github.com/aws-samples/aws2tf
Usage: terraform [global options] state show [options] ADDRESS

  Shows the attributes of a resource in the Terraform state.

  This command shows the attributes of a single resource in the Terraform
  state. The address argument must be used to specify a single resource.
  You can view the list of available resources with "terraform state list".

Options:

  -state=statefile    Path to a Terraform state file to use to look
                      up Terraform-managed resources. By default it will
                      use the state "terraform.tfstate" if it exists.
```

**Comment by awsandy** [comment]
Can you post the aws2tf.sh command you used please ..

**Comment by awsandy** [comment]
I've committed a change that might give us an additional message something like:

WARNING: aws_cloudwatch_metric_alarm terraform-test-foobar5 - not created or imported

I'm guessing this might be related to the name of the cloudwatch metric alarm - perhaps having some odd /unexpected characters.

**Comment by awsandy** [comment]
New python version (and import mechanism) should handle this ok
