### ISSUE TITLE
templete errors

### ISSUE THREAD

**Issue by arcaven** [aws-samples/aws2tf#6]
Getting a lot of template error:

aws_iam_role AWSServiceRoleForSupport
╷
│ Error: Extra characters after interpolation expression
│ 
│   on aws_iam_policy__AWSSSOServiceRolePolicy.tf line 21, in resource "aws_iam_policy" "AWSSSOServiceRolePolicy":
│   21: "aws:PrincipalOrgMasterAccountId"= "${aws:PrincipalAccount}"
│ 
│ Template interpolation doesn't expect a colon at this location. Did you
│ intend this to be a literal sequence to be processed as part of another
│ language? If so, you can escape it by starting with "$${" instead of just
│ "${".

I think it has something to do with the post-terraform 0.11.0 change from template_file to templetefile. I suspect that the older version of the terraform aws provider is calling template_file and so we're getting these suggestions to escape ${aws: to $${aws: which would probably not do what we want?

**Comment by awsandy** [comment]
That can be "fixed" by replacing ${ with &{. Updates committed
