### ISSUE TITLE
Lambda role with a period/dot is not properly handled

### ISSUE THREAD

**Issue by JoBrad** [aws-samples/aws2tf#61]
Issue: A Lambda role with a period/dot in its name is used as the Terraform resource name, causing an error when the Terraform is validated and/or executed (Note the additional `.` before `.arn`).

```
    reserved_concurrent_executions = -1
role = aws_iam_role.r-lambda-vpc-role..arn
    runtime                        = "nodejs12.x"
```

I think @awsandy actually created a patch to handle a similar situation on lines [59-60 in `050-get-iam-roles.sh`](https://github.com/aws-samples/aws2tf/blob/master/scripts/050-get-iam-roles.sh#L59):

```sh
            ocname=$(echo $cname)
            cname=${cname//./_}
```

But this doesn't catch the offending line of terraform above, which is generated on [line 133 in `700-get-lambda-function.sh`](https://github.com/aws-samples/aws2tf/blob/master/scripts/700-get-lambda-function.sh#L133).

My patch for this specific scenario is to replicate Andy's fix above, but in-line:

```sh
                        trole=$(echo $tt2 | rev | cut -f1 -d'/' | rev | tr -d '"')

                        t1=$(printf "%s = aws_iam_role.r-%s.arn" $tt1 ${trole//./_})
```

This does resolve the issue for me, and the resources are properly generated.

From my initial review of the 700 script, `t1` isn't used again, so this discrepency vs the actual resource name doesn't cause a problem later on. If I'm correct, I'm happy to submit a small PR that will make this same change for all similar lines in the script. If the other scripts use a similar architecture (I'll review a few in the meantime), then I'm happy to submit a patch for them, as well.

**Comment by awsandy** [comment]
Thank you good spot, committed fix that implements the inline everywhere it's needed for a role name

**Comment by JoBrad** [comment]
Confirmed this fixed my issue. Thanks!
