### ISSUE TITLE
small issues on first run without parameters

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#63]
1. when u first run `aws2tf.sh` without any parameters , it will take some time. 
2. the second thing is that it will say region not found and then fail on account not found. to me, logic would say the account is more important than region and should be the first check

**Comment by awsandy** [comment]
1. will be addressed by the forthcoming python version

2. committed change to check account first

**Comment by awsandy** [comment]
Closing as python version now released
