### ISSUE TITLE
no failure on non existing resource type

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#65]
i ran `./aws2tf.sh -p $AWS_PROFILE -r $AWS_REGION -t aws_internet_gateway`

it didnt really fail but i did see the error  after the `terraform init -upgrade` step with 
```
ls: ../../scripts/*-get-*aws_internet_gateway*.sh: No such file or directory
```

**Comment by marafa-sugarcrm** [comment]
1. the `ls` file not found error is still there
2. i dont think aws2tf should run terraform plan for an "unsupported" resource - perhaps that check should come in earlier?
3. the exit code is `0` for such a run. shouldnt it be a non zero? does aws2tf support that?

**Comment by awsandy** [comment]
commited change to catch this and emit non zero exit code

**Comment by marafa-sugarcrm** [comment]
goes thru configuring terraform before checking for the resource type.

**Comment by awsandy** [comment]
The new Python version should handle this a lot better
