### ISSUE TITLE
broken plan for resource type aurora

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#66]
after running `./aws2tf -p $profile -r $region -t aurora` i ran `terraform plan` and got this in the output
```
╷
│ Error: Value for unconfigurable attribute
│
│   with aws_rds_cluster.$RDS-eventlog,
│   on aws_rds_cluster__$RDS-eventlog.tf line 29, in resource "aws_rds_cluster" "$RDS-eventlog":
│   29:   master_user_secret                  = []
│
│ Can't configure a value for "master_user_secret": its value will be decided automatically based on the result of applying this configuration.
╵
╷
│ Error: Reference to undeclared resource
│
│   on aws_route_table__rtb-$RT.tf line 12, in resource "aws_route_table" "rtb-$RT":
│   12:       gateway_id                 = aws_internet_gateway.igw-$IGW.id
│
│ A managed resource "aws_internet_gateway" "igw-$IGW" has not been declared in the root module.
╵
```

**Comment by awsandy** [comment]
Is it the case that there is a "$" in the RDS cluster name ?   that looks like soem upstream automation have failed to substitute an environment variable doesn't it ??

**Comment by marafa-sugarcrm** [comment]
my bad . i was redacting the names by putting in a "variable" for the comment

**Comment by awsandy** [comment]
comitted fix that should handle the master_user_secret  problem

For the gateway id - please just check that the internet gateway mentioned in the route table still exists

They are often route table entries to resources that don't exist any more

**Comment by marafa-sugarcrm** [comment]
yes it exists. but was not generated. i pulled the file in from a different resource run and the plan was happy with the file

**Comment by marafa-sugarcrm** [comment]
after pulling in the igw i now see this
```
│ Error: Reference to undeclared resource
│
│   on aws_rds_cluster_instance__sm-prod-apse2-mercury-eventlog-1.tf line 9, in resource "aws_rds_cluster_instance" "sm-prod-apse2-mercury-eventlog-1":
│    9:   db_parameter_group_name      = aws_db_parameter_group.default-aurora5-6-logging-pg.name
│
│ A managed resource "aws_db_parameter_group" "default-aurora5-6-logging-pg" has not been declared in the root module.
╵
```

**Comment by awsandy** [comment]
committed change that *might* fix this

**Comment by marafa-sugarcrm** [comment]
uh `Filtering on type aurora unsupported see  ./aws2tf.sh -h    exiting ...`

**Comment by awsandy** [comment]
over zealous on another fix - committed a backout of that - should be ok now

**Comment by awsandy** [comment]
I'll have a think about why the igw was missed ..........
