### ISSUE TITLE
natgw resource type now broken

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#69]
this morning i ran `-t natgw` to capture some resources needed for some other resource type but was not captured.

i just ran it again and now a routing table says it cannot find a specific gateway id. 

i know i downloaded it coz i still have the file in a backup directory for one of the other resources.

after copying the files across, the plan was generated

**Comment by awsandy** [comment]
-t natgw - there is no such type, so if it worked at all it's by accident.

I've added it for you now and looked at the possible dependancies.

**Comment by marafa-sugarcrm** [comment]
still getting the error
```
Error: Reference to undeclared resource

  on aws_route_table__rtb-RTB.tf line 12, in resource "aws_route_table" "rtb-RTB":
  12:       gateway_id                 = aws_internet_gateway.igw-IGW.id

A managed resource "aws_internet_gateway" "igw-IGW" has not been declared in the root module.
```

**Comment by marafa-sugarcrm** [comment]
also, the previous run pull
- eip

**Comment by marafa-sugarcrm** [comment]
my bad - did u know `-t igw` works too (and plans without errors!)

anyways `-t ngw` has that error above and fails to generate a plan

**Comment by awsandy** [comment]
committed change to catch those stray internet gateways at validation stage
