### ISSUE TITLE
Pulling in data-aws.tf from outside of source tree generates error

### ISSUE THREAD

**Issue by arcaven** [aws-samples/aws2tf#7]
cp command pulls in file data-aws.tf from outside of the source tree ../../stubs/ path. Suggest adding some error checking to see if the file exists prior to performing the copy, so as to avoid blind execution/error for most users and/or generate or document this file if it is needed/helpful, but pull it in from somewhere safe for your use.

Existing aws2tf:
cp ../../stubs/data-aws.tf .

Example change for line above to:
DATFFILE=../../stubs/data-aws.tf
if test -f "$DATFFILE"; then
    cp $DATFFILE .
fi

I cannot offer suggestions on what should be in this file or how it could be communicated in the docs because I can only guess it's purpose.

**Comment by awsandy** [comment]
Thanks - it was accidentally "gitignored" - fixed now.
