### ISSUE TITLE
-t kinesis does not import all buckets

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#70]
`-t kinesis` does not import all buckets. the error is 
```
Error: Reference to undeclared resource

  on aws_kinesis_delivery_stream__arn_aws_KINESIS.tf line 39, in resource "aws_kinesis_delivery_stream" "arn_aws_KINESIS":
  39:       bucket_arn         = aws_s3_bucket.BUCKET_WITH_47_CHAR_NAME.arn

A managed resource "aws_s3_bucket" "BUCKET_WITH_47_CHAR_NAME" has not been declared in the root module.
```

**Comment by awsandy** [comment]
does that bucket name begin with "b_" ?

**Comment by marafa-sugarcrm** [comment]
yes

**Comment by marafa-sugarcrm** [comment]
plan still failing on missing bucket

**Comment by awsandy** [comment]
Couple of checks:
1. the bucket exists
2. Is that bucket in the same region/account as the kinesis stream ?
3. you can do from the command line :     

aws s3 ls s3://BUCKET_WITH_47_CHAR_NAME

Does the output of aws2tf.sh around the point where is gets aws_kinesis_delivery_stream__arn_aws_KINESIS.tf give any indication that it attempts to get the bucket - or any output saying it failed to get the bucket

Can I see the output of terraform state show aws_kinesis_delivery_stream.arn_aws_KINESIS.    in particular the bucket_arn line

**Comment by marafa-sugarcrm** [comment]
a) the bucket was indeed missing.
b) i set up and configured the bucket with $bucket_name
c) ran aws2.tf -t kinesis again
d) plan still fails on `b_$bucket_name`

not sure why it is adding the `b_` prefix to the bucket name

**Comment by awsandy** [comment]
the b_ on the bucket name is expected - this has to be done for the Terraform resource name as bucket names can start with a number - and Terraform resource names are not allowed to begin with a number
Next things to try:

1. rename the aws_kinesis_delivery_stream__arn_aws_KINESIS.tf file that it is erroring on to aws_kinesis_delivery_stream__arn_aws_KINESIS.tf.sav

2. post the output of 

terraform state show aws_kinesis_delivery_stream.arn_aws_KINESIS | grep bucket 

here

Then you could try this to confirm it works:

./aws2tf.sh -t s3 -i $bucket_name -c yes.           

The -c yes - "continues" so the current stuff will remain untouched.
no need for the b_ on the bucket name - that's something internal to aws2tf (as explained above)

**Comment by marafa-sugarcrm** [comment]
pebkac. bucket properly imported now
