### ISSUE TITLE
`-t route53` missing

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#71]
hi 
can you add `-t route53` as a resource type to scan?

thank you

**Comment by awsandy** [comment]
There's some basic route53 capability (-t route53) in the python version:

./aws2tf.py -t route53

(hosted zones and A records only at the mopment)

If there's other route53 things missing you need - comment here and I'll try to add them in

**Comment by awsandy** [comment]
please open issue of more route53 capability is needed for the aws2tf.py version
