### ISSUE TITLE
Method to exclude via regex or config

### ISSUE THREAD

**Issue by k6ef** [aws-samples/aws2tf#73]
While importing the IAM resources, the import errors out due to EKS  failures due to likely lack of user permissions within the IAM profile being used to import the resources. In my case, the EKS deployments are automated and I don't need to import those roles into the general TF import. I wish to exclude the EKS related resources.

**Comment by awsandy** [comment]
The new Python version should address this (If I've understood your problem statement correctly)

Please reopen if it's still an issue
