### ISSUE TITLE
aws_api_gateway_resource not being imported 

### ISSUE THREAD

**Issue by zakrzk** [aws-samples/aws2tf#74]
Tool only generates code for `aws_api_gateway_rest_api` resources, but it doesn't generate code for the resources belonging to that REST API.

Steps to reproduce:
- ` ./aws2tf.sh -t apigw -i abc123`

File generated by the above command would look like:

```
# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_api_gateway_rest_api.abc123:
resource "aws_api_gateway_rest_api" "abc123" {
  api_key_source               = "HEADER"
  binary_media_types           = []
  description                  = "Test"
[...]
}

```      

There's no file with `aws_api_gateway_resource` belonging to the API, but, according to the docs, this is supported

> Terraform resources supported as of 08-Oct-2023
> aws_acm_certificate
> aws_api_gateway_resource
> aws_api_gateway_rest_api
> [...]

**Comment by awsandy** [comment]
committed change that should fix this

**Comment by zakrzk** [comment]
Thank you, that worked! :)
