### ISSUE TITLE
API Gateway - only GET methods are being imported

### ISSUE THREAD

**Issue by zakrzk** [aws-samples/aws2tf#75]
Hey,

I noticed that while importing API Gateway resources only `GET` methods are being imported.

Steps to reproduce:

- ./aws2tf.sh -t apigw -i abc123

while the REST API with ID `abc123` must have multiple methods i.e. `GET`, `POST` and `OPTIONS`

the command exits successfully, the tool generates code for `aws_api_gateway_resource` and `aws_api_gateway_method` but does it only for methods that have ` http_method = "GET"`

Is there any chance you could implement this additional functionality so other types of methods would be supported as well?

Thanks!

**Comment by awsandy** [comment]
committed changes to fix this
