### ISSUE TITLE
There is an issue with importing EC2 resources

### ISSUE THREAD

**Issue by jiangzhengguan** [aws-samples/aws2tf#78]
hi， When I execute ./aws2tf.py - t ec2- r us east-1 When importing ec2 resources, I found that it can only import 3 ec2 instances and other related resources. However, the actual situation is that we have more than 3 ec2 instances in us east-1, and then I tried to execute it again ./aws2tf.sh -t ec2 -r us-east-1, A large number of errors have occurred, similar to the following
│ Error: Reference to undeclared resource
│ 
│   on aws_instance__i-08f61118879098007.tf line 92, in resource "aws_instance" "i-08f61118879098007":
│   92: kms_key_id = data.aws_kms_key.k_null.arn

**Comment by awsandy** [comment]
Commited chnages that should:

a. ensure ./aws2tf.py     should get all your instances (not just 3 of them)

b. fixes the kms_key_id null problem in aws2tf.sh

**Comment by jiangzhengguan** [comment]
and these errors
Error: Reference to undeclared resource

  on aws_route_table__rtb-0e5cff331396acc42.tf line 16, in resource "aws_route_table" "rtb-0e5cff331396acc42":
  16:       network_interface_id       = aws_network_interface.null.id

A managed resource "aws_network_interface" "null" has not been declared in the root module.

Error: Reference to undeclared resource

  on aws_route_table__rtb-0e5cff331396acc42.tf line 17, in resource "aws_route_table" "rtb-0e5cff331396acc42":
  17:       transit_gateway_id         = aws_ec2_transit_gateway.null.id

A managed resource "aws_ec2_transit_gateway" "null" has not been declared in the root module.

Error: Reference to undeclared resource

  on aws_route_table__rtb-0f735d953c2ba0206.tf line 16, in resource "aws_route_table" "rtb-0f735d953c2ba0206":
  16:       network_interface_id       = aws_network_interface.null.id

A managed resource "aws_network_interface" "null" has not been declared in the root module.

Error: Reference to undeclared resource

  on aws_route_table__rtb-0f735d953c2ba0206.tf line 17, in resource "aws_route_table" "rtb-0f735d953c2ba0206":
  17:       transit_gateway_id         = aws_ec2_transit_gateway.null.id

A managed resource "aws_ec2_transit_gateway" "null" has not been declared in the root module.

**Comment by jiangzhengguan** [comment]
Sorry, please ignore the issue mentioned above
