### ISSUE TITLE
DMS cannot be imported normally

### ISSUE THREAD

**Issue by jiangzhengguan** [aws-samples/aws2tf#79]
Hi,when i execute ./aws2tf.py -t dms，the log shows "The parameter Logging.CloudWatchLogStream is read-only and cannot be set." at the end

**Comment by awsandy** [comment]
Can you give me a  pointer to which terraform resource type is associated with that error - so I reproduce it and fix.

**Comment by jiangzhengguan** [comment]
thanks，the issues mentioned above have been fixed, but when I execute  ./aws2tf.py -t ec2 -m, the logs shows these errors
Error: Reference to undeclared resource

  on aws_dms_replication_instance__share-wick-adtomic-amazon.tf line 31, in resource "aws_dms_replication_instance" "share-wick-adtomic-amazon":
  31:   vpc_security_group_ids = [aws_security_group.sg-096ed6b075bb5ed2b.id]

A managed resource "aws_security_group" "sg-096ed6b075bb5ed2b" has not been
declared in the root module.

Error: Reference to undeclared resource

  on aws_dms_replication_instance__share-wick-adtomic-walmart.tf line 31, in resource "aws_dms_replication_instance" "share-wick-adtomic-walmart":
  31:   vpc_security_group_ids = [aws_security_group.sg-096ed6b075bb5ed2b.id]

A managed resource "aws_security_group" "sg-096ed6b075bb5ed2b" has not been
declared in the root module.

Error: Reference to undeclared resource

  on aws_nat_gateway__nat-030df4f73fc064fe3.tf line 7, in resource "aws_nat_gateway" "nat-030df4f73fc064fe3":
   7:   subnet_id                      = aws_subnet.subnet-031077dbb7484636a.id

A managed resource "aws_subnet" "subnet-031077dbb7484636a" has not been
declared in the root module.

Error: Reference to undeclared resource

  on aws_route_table_association__subnet-031077dbb7484636a_rtb-013d0cc094e8889fb.tf line 4, in resource "aws_route_table_association" "subnet-031077dbb7484636a_rtb-013d0cc094e8889fb":
   4:   subnet_id      = aws_subnet.subnet-031077dbb7484636a.id

A managed resource "aws_subnet" "subnet-031077dbb7484636a" has not been
declared in the root module.

**Comment by awsandy** [comment]
Hi

Hmm - not quite sure why those dependancies have't been picked up - could you try getting them manually with:

./aws2tf.py -t aws_security_group -i sg-096ed6b075bb5ed2b -m
&
./aws2tf.py -t aws_subnet -i subnet-031077dbb7484636a -m

And see if these exist / are picked up.

I'll look at catching this kind of thing another way as well ...

**Comment by awsandy** [comment]
Have reproduced the problem - there's a bug in the merge (-m) logic somewhere - will advise when it's fixed.

**Comment by awsandy** [comment]
Merging should be fixed now
