### ISSUE TITLE
Tags_all on RDS shows a change 

### ISSUE THREAD

**Issue by anaassh** [aws-samples/aws2tf#89]
Tags_all on RDS shows an in place change even though the TF files and state include it in there? It doesnt happen to other services, such as EC2, DynamoDB ect. 

Do you know why this is the case? 

Terraform will perform the following actions:

  # aws_db_instance.test-e2etesting01-123456464-myrdsinstance-123456789 will be updated in-place
  ~ resource "aws_db_instance" "test-e2etesting01-123456789-myrdsinstance-123456789" {
        id                                    = "db-123456789"
        tags                                  = {
            "Name" = "test-eu-west-1-rds-123456789"
        }
        # (53 unchanged attributes hidden)
    }

  # aws_db_instance.test-e2etesting02-123456789-myrdsinstance-123456789 will be updated in-place
  ~ resource "aws_db_instance" "test-e2etesting02-123456789-myrdsinstance-123456789" {
        id                                    = "db-123456789"
        tags                                  = {
            "Name" = "test-eu-west-2-rds-123456789"
        }
        # (53 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.

**Comment by awsandy** [comment]
I note this has been closed - is it still an issue for you ?
