### ISSUE TITLE
Inaccuracy in the README

### ISSUE THREAD

**Issue by statox** [aws-samples/aws2tf#9]
Hi :wave: 

The README of this repo [says](https://github.com/aws-samples/aws2tf/blob/master/README.md?plain=1#L69-L72):

> To include AWS account Policies and Roles:
> ```
> ./aws2tf.sh -p yes
> ```

But the `-h` help [says otherwise](https://github.com/aws-samples/aws2tf/blob/master/aws2tf.sh#L3):

>    -p <profile> specify the AWS profile to use (Default=\"default\")

I'm not sure what the original intent of the README was but it looks like it's outdated.

Also it looks like `-d yes` allow to dump secrets to `.tf` files but the help could be a bit more explicit about that:

>     -d <yes|no|st> (default=no)   Debug - lots of output if yes

**Comment by awsandy** [comment]
Readme updated,  added caution output when using ./aws2tf.sh with -d

**Comment by statox** [comment]
Cool! Thank you for the quick fix!
And congrats on your job this is a cool tool :)
