### ISSUE TITLE
Import All, 

### ISSUE THREAD

**Issue by jdonalson** [aws-samples/aws2tf#90]
hangs on 746 of 1306	aws_licensemanager_association
Not supported by aws2tf currently: aws_licensemanager_association please submit github issue to request support
747 of 1306	aws_licensemanager_grant
Not supported by aws2tf currently: aws_licensemanager_grant please submit github issue to request support
748 of 1306	aws_licensemanager_grant_accepter
Not supported by aws2tf currently: aws_licensemanager_grant_accepter please submit github issue to request support
749 of 1306	aws_licensemanager_license_configuration

ERROR: in call_boto3 clfn=license-manager descfn=list_license_configurations topkey=LicenseConfigurations id=None
e=IndexError('list index out of range') [e1]
common.py 1282

**Comment by awsandy** [comment]
looking ........

**Comment by awsandy** [comment]
committed changes that should(?) fix this

**Comment by jdonalson** [comment]
fixed
